spring:
  application:
    name: my-stickers-bot

bot:
  webhook: false
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}
  service-account-id: ${SERVICE_ACCOUNT_ID}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
