spring:
  application:
    name: my-stickers-bot
  messages:
    fallback-to-system-locale: false

bot:
  webhook: false
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}
  service-account-id: ${SERVICE_ACCOUNT_ID}


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
logging:
  level:
    com.vdsirotkin: debug
    io.github.biezhi: debug
