spring:
  application:
    name: my-stickers-bot
  messages:
    fallback-to-system-locale: false
  security:
    user:
      name: admin
      password: ${ADMIN_PASS:admin}
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/
      database: my_sticker_bot


bot:
  webhook: false
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}
  service-account-id: ${SERVICE_ACCOUNT_ID:0}


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
logging:
  level:
    com.vdsirotkin: debug
    com.vdsirotkin.telegram.mystickersbot.util.security.CustomRequestCache: error
    io.github.biezhi: debug

vaadin:
  heartbeatInterval: 5
dashbot:
  enabled: false
  api-key: ${DASHBOT_API_KEY}
ssh:
  shell:
    user: admin
    password: ${ADMIN_PASS:admin}
